language: php

php:
  - 5.5
  - 5.6

install:
  - composer --no-interaction install

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml test

after_script:
  - wget http://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
