language: php

php:
  - 5.5
  - 5.6

install:
  - composer -n require satooshi/php-coveralls:dev-master

script:
  - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml test

after_script:
  # Scrutinizer coverage.
  - wget http://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

  # Coveralls coverage.
  - vendor/bin/coveralls
